/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection JSUnusedGlobalSymbols
// Generated by unplugin-auto-import
// biome-ignore lint: disable
export {}
declare global {
  const IconMaterialSymbolsCalendarAppsScript: typeof import('~icons/material-symbols/calendar-apps-script')['default']
  const IconSolarClipboardAddBold: typeof import('~icons/solar/clipboard-add-bold')['default']
  const IconSolarUsersGroupRoundedBold: typeof import('~icons/solar/users-group-rounded-bold')['default']
  const IconTablerClipboardDataFilled: typeof import('~icons/tabler/clipboard-data-filled')['default']
}
