/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppConfig: typeof import('./src/components/app/appConfig.vue')['default']
    BasicFormToAddOrEdit: typeof import('./src/components/app/basicFormToAddOrEdit.vue')['default']
    Button: typeof import('primevue/button')['default']
    Card: typeof import('primevue/card')['default']
    EmptyTable: typeof import('./src/components/emptyTable.vue')['default']
    FormItem: typeof import('./src/components/formItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ICarbonColorPalette: typeof import('~icons/carbon/color-palette')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IIcBaselineTextIncrease: typeof import('~icons/ic/baseline-text-increase')['default']
    IIcRoundDarkMode: typeof import('~icons/ic/round-dark-mode')['default']
    IIcRoundLightMode: typeof import('~icons/ic/round-light-mode')['default']
    IIcTwotoneTextDecrease: typeof import('~icons/ic/twotone-text-decrease')['default']
    IMaterialSymbolsCircle: typeof import('~icons/material-symbols/circle')['default']
    IMaterialSymbolsKeyboardArrowDownRounded: typeof import('~icons/material-symbols/keyboard-arrow-down-rounded')['default']
    IMaterialSymbolsPersonOutlineRounded: typeof import('~icons/material-symbols/person-outline-rounded')['default']
    INotoTurtle: typeof import('~icons/noto/turtle')['default']
    InputText: typeof import('primevue/inputtext')['default']
    ISolarHamburgerMenuBroken: typeof import('~icons/solar/hamburger-menu-broken')['default']
    LoadingPage: typeof import('./src/components/loadingPage.vue')['default']
    Menubar: typeof import('primevue/menubar')['default']
    ModalComponent: typeof import('./src/components/modalComponent.vue')['default']
    Permissions: typeof import('./src/components/app/permissions.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheNavbar: typeof import('./src/components/TheNavbar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    ToggleButton: typeof import('primevue/togglebutton')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
